version: "3"

services:
  naming-server:
    build: naming_server
    image: regzon/dfs-naming-server
    environment:
      UWSGI_PROCESSES: $NAMING_UWSGI_PROCESSES
      UWSGI_THREADS: $NAMING_UWSGI_THREADS
      DJANGO_SECRET_KEY: $NAMING_DJANGO_SECRET_KEY
      DJANGO_ALLOWED_HOSTS: $NAMING_DJANGO_ALLOWED_HOSTS
      DJANGO_DEBUG: $NAMING_DJANGO_DEBUG
    volumes:
      - database:/application/database
    ports:
      - "127.0.0.1:80:80"

  storage-server-1:
    build: storage_server
    image: regzon/dfs-storage-server
    environment:
      UWSGI_PROCESSES: $STORAGE_UWSGI_PROCESSES
      UWSGI_THREADS: $STORAGE_UWSGI_THREADS
      NAMING_SERVER: "http://naming-server"
    ports:
      - "127.0.0.1:5000:5000"

  storage-server-2:
    build: storage_server
    image: regzon/dfs-storage-server
    environment:
      UWSGI_PROCESSES: $STORAGE_UWSGI_PROCESSES
      UWSGI_THREADS: $STORAGE_UWSGI_THREADS
      NAMING_SERVER: "http://naming-server"
    ports:
      - "127.0.0.1:5000:5000"

volumes:
  database:
