name: Docker Image CI

on: [push]

jobs:

  build_storage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build storage server
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: regzon/dfs-storage-server
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          workdir: storage_server
          tag_names: true


  build_naming:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build naming server
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: regzon/dfs-naming-server
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          workdir: naming_server
          tag_names: true
